apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculadora
  template:
    metadata:
      labels:
        app: calculadora
    spec:
      containers:
        - name: calculadora
          image: nestjs-calculadora:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
